[project]
name = "aoc2025"
version = "0.1.0"
description = "Repo to solve Advent of Code 2025 problems"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "elf>=1.1.0",
    "ipython>=9.7.0",
    "polars>=1.35.2",
    "rust-just>=1.43.1",
]
